/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AdminImport } from './routes/admin'
import { Route as IndexImport } from './routes/index'
import { Route as PlayersIndexImport } from './routes/players/index'
import { Route as PlayersCreateImport } from './routes/players/create'
import { Route as PlayersPlayerIdImport } from './routes/players/$playerId'
import { Route as PlayersPlayerIdEditImport } from './routes/players/$playerId.edit'

// Create/Update Routes

const AdminRoute = AdminImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PlayersIndexRoute = PlayersIndexImport.update({
  id: '/players/',
  path: '/players/',
  getParentRoute: () => rootRoute,
} as any)

const PlayersCreateRoute = PlayersCreateImport.update({
  id: '/players/create',
  path: '/players/create',
  getParentRoute: () => rootRoute,
} as any)

const PlayersPlayerIdRoute = PlayersPlayerIdImport.update({
  id: '/players/$playerId',
  path: '/players/$playerId',
  getParentRoute: () => rootRoute,
} as any)

const PlayersPlayerIdEditRoute = PlayersPlayerIdEditImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => PlayersPlayerIdRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminImport
      parentRoute: typeof rootRoute
    }
    '/players/$playerId': {
      id: '/players/$playerId'
      path: '/players/$playerId'
      fullPath: '/players/$playerId'
      preLoaderRoute: typeof PlayersPlayerIdImport
      parentRoute: typeof rootRoute
    }
    '/players/create': {
      id: '/players/create'
      path: '/players/create'
      fullPath: '/players/create'
      preLoaderRoute: typeof PlayersCreateImport
      parentRoute: typeof rootRoute
    }
    '/players/': {
      id: '/players/'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof PlayersIndexImport
      parentRoute: typeof rootRoute
    }
    '/players/$playerId/edit': {
      id: '/players/$playerId/edit'
      path: '/edit'
      fullPath: '/players/$playerId/edit'
      preLoaderRoute: typeof PlayersPlayerIdEditImport
      parentRoute: typeof PlayersPlayerIdImport
    }
  }
}

// Create and export the route tree

interface PlayersPlayerIdRouteChildren {
  PlayersPlayerIdEditRoute: typeof PlayersPlayerIdEditRoute
}

const PlayersPlayerIdRouteChildren: PlayersPlayerIdRouteChildren = {
  PlayersPlayerIdEditRoute: PlayersPlayerIdEditRoute,
}

const PlayersPlayerIdRouteWithChildren = PlayersPlayerIdRoute._addFileChildren(
  PlayersPlayerIdRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/players/$playerId': typeof PlayersPlayerIdRouteWithChildren
  '/players/create': typeof PlayersCreateRoute
  '/players': typeof PlayersIndexRoute
  '/players/$playerId/edit': typeof PlayersPlayerIdEditRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/players/$playerId': typeof PlayersPlayerIdRouteWithChildren
  '/players/create': typeof PlayersCreateRoute
  '/players': typeof PlayersIndexRoute
  '/players/$playerId/edit': typeof PlayersPlayerIdEditRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/players/$playerId': typeof PlayersPlayerIdRouteWithChildren
  '/players/create': typeof PlayersCreateRoute
  '/players/': typeof PlayersIndexRoute
  '/players/$playerId/edit': typeof PlayersPlayerIdEditRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/players/$playerId'
    | '/players/create'
    | '/players'
    | '/players/$playerId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/players/$playerId'
    | '/players/create'
    | '/players'
    | '/players/$playerId/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/players/$playerId'
    | '/players/create'
    | '/players/'
    | '/players/$playerId/edit'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  PlayersPlayerIdRoute: typeof PlayersPlayerIdRouteWithChildren
  PlayersCreateRoute: typeof PlayersCreateRoute
  PlayersIndexRoute: typeof PlayersIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  PlayersPlayerIdRoute: PlayersPlayerIdRouteWithChildren,
  PlayersCreateRoute: PlayersCreateRoute,
  PlayersIndexRoute: PlayersIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/admin",
        "/players/$playerId",
        "/players/create",
        "/players/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/admin": {
      "filePath": "admin.tsx"
    },
    "/players/$playerId": {
      "filePath": "players/$playerId.tsx",
      "children": [
        "/players/$playerId/edit"
      ]
    },
    "/players/create": {
      "filePath": "players/create.tsx"
    },
    "/players/": {
      "filePath": "players/index.tsx"
    },
    "/players/$playerId/edit": {
      "filePath": "players/$playerId.edit.tsx",
      "parent": "/players/$playerId"
    }
  }
}
ROUTE_MANIFEST_END */
